export default [
  {
    name: 'ARKOSE',
    number: '33',
    street: 'Rue du Progrès',
    zipcode: '93100',
    city: 'Montreuil',
    country: 'France',
    longitude: '48.85186663238125',
    latitude: '2.4192897136670743',
    discipline: 'Bloc/voie',
    type: 'Salle',
    rock_type: '',
    picture: 'https://www.grimper.com/media/guide_salles/img_salles/arkose_montreuil_5_arkose.jpg',
    various: "Une super salle d'escalade à côté de Paris",
    reputation: 'medium',
    min_difficulty: '5a',
    max_difficulty: '9a',
  },
  {
    name: 'Art Bloc',
    number: '23',
    street: 'Avenue Auguste Verola',
    zipcode: '06200',
    city: 'Nice',
    country: 'France',
    longitude: '43.71030850974363',
    latitude: '7.193304772923666',
    discipline: 'Bloc',
    type: 'Salle',
    rock_type: '',
    picture: 'https://static.apidae-tourisme.com/filestore/objets-touristiques/images/123/185/9615739.jpg',
    various: 'Une salle d\'escalade en plein coeur de Nice, ouvert 7j/7',
    reputation: 'easy',
    min_difficulty: '6d',
    max_difficulty: '9b',
  },
  {
    name: 'Fontainebleu-Les trois pignons',
    number: '',
    street: '',
    zipcode: '77123',
    city: 'Noisy-sur-ecole',
    country: 'France',
    longitude: '48.38602355341682',
    latitude: '2.521116378201298',
    discipline: 'Bloc',
    type: 'Spot',
    rock_type: 'craie',
    picture: 'https://www.montagnes-magazine.com/media/actu/2020/05/jef-willemyns-mluUYXoTotY-unsplash.jpg',
    various: 'lorem impsum lorem carium',
    reputation: '',
    min_difficulty: '5c',
    max_difficulty: '8a',
  },
  {
    name: 'BIBEMUS Les carrières de Cézanne',
    number: '3080',
    street: '',
    zipcode: '13100',
    city: 'Aix-en-Provence',
    country: 'France',
    longitude: '43.53074657951234',
    latitude: '5.499217430680994',
    discipline: 'Bloc',
    type: 'Spot',
    rock_type: 'Grès',
    picture: 'https://www.blockout.fr/images/articles/Nantes.jpg',
    various: 'Site de bloc "style pan", c\'est à nous d\'inventer les blocs, prises taillées en nombre',
    reputation: '',
    min_difficulty: '3a',
    max_difficulty: '7a',
  },
  {
    name: 'The Roof - Maison de l\'Escalade - Pays Basque',
    number: '3',
    street: 'Pl. André Emlinger',
    zipcode: '64100',
    city: 'Bayonne',
    country: 'France',
    longitude: '43.49174705055953',
    latitude: '-1.4935901536720693',
    discipline: 'bloc',
    type: 'interieur',
    rock_type: '',
    picture: 'https://www.grimper.com/media/guide_salles/img_salles/the_roof_pays_basque2.jpg',
    various: 'en toute objectivité, la meilleure salle du monde.',
    reputation: 'easy',
    min_difficulty: '5a',
    max_difficulty: '9a',
  },

];
